"""!
@file main.py
@brief Entry point for integrating chess state parsing, planning, and robot motion execution.
"""

import asyncio
import time
import chess
import numpy as np
import gpiozero

from Electromagnet import Electromagnet
from ServoController import ServoController
from ChessStateValidatorMoveParser import ChessBoard
from RobotMotionPlanner import RobotMotionPlanner
from InverseKinematics_TrajectoryPlanner import (
    chess_robot_inversekinematics,
    cubic_spline,
    fifth_order_spline,
)
from EndGameEffectorTask import EndgameEffectorFSM
from UITask import UITaskFSM, init_ui_runtime, app as ui_app
import uvicorn
def main():
    """!
    @brief Runs a full sequence test from FEN parsing to robot waypoint generation. 
    """
    """
    @brief Application entry point for the chess robot control loop.
    """
    #flowchart of the main function:
    #1. Initialize the chess board, robot motion planner, servo controller, and computer vision system
    #3 wait for a move to be made on the chess board
    #run the computer vision system to detect the move 
    #put the detected move in the chessboard object to validate it and update the chess board state
    #4. If the move is valid, use parsemove() to parse the move into chessspace waypoints 
    #use the robot motion planner to generate manipulator space waypoints for the move using
    #5.parse_chesswaypoints() inputting the chessspace  and output the manipulator space 
    # waypoints for the robot to execute the move
    #6. Use the inverse kinematics to change the list of waypoints in manipulator space 
    # to joint space waypoints for the robot to execute the move
    #7. Use the trajectory planner to generate a trajectory for the robot to move from its
    # current waypoint to the next waypoint target using a fifth-order spline trajectory
    #8. query the trajectory planner for the next trajectory segment to execute and send the joint angle commands to the robot
    """!
    @brief uses asyncio to run cooperative multitasking. to run the main control loop of the chess robot software, which includes:
        cv task:
        - running the computer vision system to detect the move made on the chess board

        endgame effector cpu task:
        - validating the detected move and updating the chess board state
        - generating chessspace waypoints for the move using the chess board's parsemove() function
        - converting the chessspace waypoints to manipulator space waypoints using the robot motion planner's parse_chesswaypoints() function
        - converting the manipulator space waypoints to joint space waypoints using the inverse kinematics function
        - using the trajectory planner to generate a trajectory for the robot to move from its current waypoint to the next waypoint target using a fifth-order spline trajectory
        - querying the trajectory planner for the next trajectory segment to execute and sending the joint angle commands to the robot
        
        servo controller task:
        - managing the robot's servo control loop to execute the 
        joint angle commands generated by the trajectory planner   
        
        ui task:
        - updating the UI with the current board state and any relevant information
       
        low-level sensor control task:
        - manage the electromagnetic
        and limit switch and possible LEDS
    """
    #initialize the chess board and robot motion planner
    chess_board = ChessBoard()
    motion_planner = RobotMotionPlanner()
    servo_controller = ServoController()
    #initialize low level hardware controllers
    EMAG = Electromagnet(pin=17)
    #########################################################
    #event and queue definitions for inter-task communication
    #########################################################
    #events that represent flags for inter-task communication and synchronization
    begin_game = asyncio.Event()  # Event to signal the start of the game after initialization
    use_cv = asyncio.Event()  # Event to signal whether we will use CV or manual input for moves
    ready2move = asyncio.Event()  # Event to signal that the opponents move is complete 
    #meaning the robot can process the current move and execute the next move
    emag_on = asyncio.Event()  # Event to signal when to turn on the electromagnet for piece manipulation
    emag_off = asyncio.Event()  # Event to signal when to turn off the electromagnet
    move_completed = asyncio.Event()  # Event to signal that the robot has completed its move 
    servo_mode = asyncio.Event()  # Event to signal when to switch the servo control mode
    valid_move = asyncio.Event()  # Event to signal that the detected move has been validated and parsed successfully
    #########################################################
    #queues to hold data that needs to be passed between tasks
    winner = asyncio.Queue() # Queue for the winner of the game,
    #updated by the endgame effector CPU task and read by the UI task to display
    opponent_move = asyncio.Queue() # Queue for opponent moves inputted in UI or detected by CV 
    #depending on the game mode
    theta_vector = asyncio.Queue() # Queue for the current joint angles of the robot, 
    #updated by the cpu task and read by the servo controller task for motion execution
    detected_fen = asyncio.Queue() # Queue for the detected FEN string after a move is made,
    #updated by the CV task and read by the endgame effector CPU task for move validation
    winner = asyncio.Queue() # Queue for the winner of the game, 
    #updated by the endgame effector CPU task and read by the UI task to display
    update_ui_boardstate = asyncio.Queue() # Queue for the current board state to be displayed in the UI,
    update_ui_robot_waypoints = asyncio.Queue() # Queue for the current robot waypoints to be displayed in the UI,
    update_ui_move_list = asyncio.Queue() # Queue for the move list to be displayed in the UI
    promotion_piece = asyncio.Queue() # Queue for the piece type to promote to in a pawn promotion scenario,
    #updated by the endgame effector CPU task and read by the UI task to display promotion options and get 
    #user input to place the piece in the promotion square
    ###########################################################################

    #asyncio tasks
    async def servo_controller_task():
        while True:
            #wait for the servo mode event to be set, which signals that the robot should execute the next move
            await servo_mode.wait()
            #read the current joint angles from the theta_vector queue
            current_thetas = await theta_vector.get()
            #send the joint angle commands to the robot's servo controller to execute the move
            print(f"Updating servo positions to: {current_thetas}")
            servo_controller.update_servo_positions(current_thetas)
    
    async def cv_task():
        while True:
            #run the computer vision system to detect the move 
            #put the detected move in the chessboard object to validate it and update the chess board state
            await asyncio.sleep(0.1)  # Simulate CV processing delay
    
    async def endgameeffector_cpu_task():
        # Create queues and events dictionaries for FSM
        queues = {
            'opponent_move': opponent_move,
            'detected_fen': detected_fen,
            'theta_vector': theta_vector,
            'update_ui_boardstate': update_ui_boardstate,
            'update_ui_robot_waypoints': update_ui_robot_waypoints,
            'winner': winner
        }
        events = {
            'begin_game': begin_game,
            'ready2move': ready2move,
            'servo_mode': servo_mode,
            'use_cv': use_cv,
            'emag_on': emag_on,
            'emag_off': emag_off,
            'valid_move': valid_move,
            'move_completed': move_completed,
        }
        # Create and run the FSM
        fsm = EndgameEffectorFSM(queues, events, chess_board, motion_planner)
        await fsm.run()
    
    async def ui_task():
        # Start the uvicorn web server for the FastAPI app
        config = uvicorn.Config(ui_app, host="127.0.0.1", port=8000, log_level="info")
        server = uvicorn.Server(config)
        await server.serve()

    async def lowlevel_sensorcontrol_task():
        while True:
            await emag_on.wait()  # Wait for the signal to turn on the electromagnet
            print("Electromagnet ON for piece manipulation.")
            EMAG.on()
            emag_on.clear()  # Reset for next use
            
            await emag_off.wait()  # Wait for the signal to turn off the electromagnet
            print("Electromagnet OFF after piece manipulation.")
            EMAG.off()
            emag_off.clear()  # Reset for next use


    ui_queues = {
        'detected_fen': detected_fen,
        'winner': winner,
        'update_ui_boardstate': update_ui_boardstate,
        'update_ui_robot_waypoints': update_ui_robot_waypoints,
        'update_ui_move_list': update_ui_move_list,
        'opponent_move': opponent_move,
    }
    ui_events = {
        'begin_game': begin_game,
        'ready2move': ready2move,
        'move_completed': move_completed,
        'valid_move': valid_move,
        'use_cv': use_cv,
    }
    init_ui_runtime(ui_queues, ui_events, chess_board, motion_planner)

    #run the tasks concurrently
    async def run_all_tasks():
        await asyncio.gather(
            cv_task(),
            servo_controller_task(),
            endgameeffector_cpu_task(),
            ui_task(),
            lowlevel_sensorcontrol_task()
        )
    
    asyncio.run(run_all_tasks())
        
if __name__ == "__main__":
    main()

