"""!
@file main.py
@brief Entry point for integrating chess state parsing, planning, and robot motion execution.
"""

import asyncio
import time
import chess
import numpy as np
from .ChessStateValidatorMoveParser import ChessBoard
from .RobotMotionPlanner import RobotMotionPlanner
from .test_classes import _patch_chessboard_contract_for_robot_planner, plot_robot_waypoints
from .InverseKinematics_TrajectoryPlanner import (
    chess_robot_inversekinematics,
    cubic_spline,
    fifth_order_spline,
)
def main():
    """!
    @brief Runs a full sequence test from FEN parsing to robot waypoint generation. 
    """
    """
    @brief Application entry point for the chess robot control loop.
    """
    #flowchart of the main function:
    #1. Initialize the chess board and robot motion planner
    #3 wait for a move to be made on the chess board
    #run the computer vision system to detect the move 
    #put the detected move in the chessboard object to validate it and update the chess board state
    #4. If the move is valid, use parsemove() to parse the move into chessspace waypoints 
    #use the robot motion planner to generate manipulator space waypoints for the move using
    #5.parse_chesswaypoints() inputting the chessspace waypoints
    #6. Use the inverse kinematics to change the list of waypoints in manipulator space 
    # to joint space waypoints for the robot to execute the move
    #7. Use the trajectory planner to generate a trajectory for the robot to move from its
    # current waypoint to the next waypoint target using a fifth-order spline trajectory
    #8. query the trajectory planner for the next trajectory segment to execute and send the joint angle commands to the robot
    """!
    @brief uses asyncio to run cooperative multitasking. to run the main control loop of the chess robot software, which includes:
        cv task:
        - running the computer vision system to detect the move made on the chess board

        endgame effector cpu task:
        - validating the detected move and updating the chess board state
        - generating chessspace waypoints for the move using the chess board's parsemove() function
        - converting the chessspace waypoints to manipulator space waypoints using the robot motion planner's parse_chesswaypoints() function
        - converting the manipulator space waypoints to joint space waypoints using the inverse kinematics function
        - using the trajectory planner to generate a trajectory for the robot to move from its current waypoint to the next waypoint target using a fifth-order spline trajectory
        - querying the trajectory planner for the next trajectory segment to execute and sending the joint angle commands to the robot
        
        servo controller task:
        - managing the robot's servo control loop to execute the 
        joint angle commands generated by the trajectory planner   
        
        ui task:
        - updating the UI with the current board state and any relevant information
       
        low-level sensor control task:
        - manage the electromagnetic
        and limit switch and possible LEDS
    """
    #asyncio tasks
    async def servo_controller_task():
        while True:
            #query the trajectory planner for the next trajectory segment to execute and send the joint angle commands to the robot
            await asyncio.sleep(0.1)  # Simulate control loop delay
    async def cv_task():
        while True:
            #run the computer vision system to detect the move 
            #put the detected move in the chessboard object to validate it and update the chess board state
            await asyncio.sleep(0.5)  # Simulate CV processing delay
    async def endgameeffector_cpu_task():
        while True:
            #run the computer vision system to detect the move 
            #put the detected move in the chessboard object to validate it and update the chess board state
            await asyncio.sleep(0.5)  # Simulate endgame effector processing delay
    async def ui_task():
        while True:
            #wait for a move to be made on the chess board
            #update the UI with the current board state and any relevant information
            await asyncio.sleep(1.0)  # Simulate UI update delay
    async def lowlevel_sensorcontrol_task():
        while True:
            #monitor the robot's sensors for any issues or feedback during motion execution
            await asyncio.sleep(0.1)  # Simulate sensor monitoring delay
    #run the tasks concurrently
    loop = asyncio.get_event_loop()
    loop.create_task(cv_task())
    loop.create_task(servo_controller_task())
    loop.create_task(endgameeffector_cpu_task())
    loop.create_task(ui_task())
    loop.create_task(lowlevel_sensorcontrol_task())
    loop.run_forever()
        
if __name__ == "__main__":
    main()