"""!
@file main.py
@brief Entry point for integrating chess state parsing, planning, and robot motion execution.
"""

import asyncio
from os import read
import time
import chess
import numpy as np
import gpiozero

import cv_fen.board_to_fen as board_to_fen
from Electromagnet import Electromagnet
from ServoController import ServoController
from ChessStateValidatorMoveParser import ChessBoard
from RobotMotionPlanner import RobotMotionPlanner
from InverseKinematics_TrajectoryPlanner import (
    chess_robot_inversekinematics,
    cubic_spline,
    fifth_order_spline,
)
from EndGameEffectorTask import EndgameEffectorFSM
from UITask import UITaskFSM, init_ui_runtime, app as ui_app
import uvicorn
def main():
    """!
    @brief Runs a full sequence test from FEN parsing to robot waypoint generation. 
    """
    """
    @brief Application entry point for the chess robot control loop.
    """
    #flowchart of the main function:
    #1. Initialize the chess board, robot motion planner, servo controller, and computer vision system
    #3 wait for a move to be made on the chess board
    #run the computer vision system to detect the move 
    #put the detected move in the chessboard object to validate it and update the chess board state
    #4. If the move is valid, use parsemove() to parse the move into chessspace waypoints 
    #use the robot motion planner to generate manipulator space waypoints for the move using
    #5.parse_chesswaypoints() inputting the chessspace  and output the manipulator space 
    # waypoints for the robot to execute the move
    #6. Use the inverse kinematics to change the list of waypoints in manipulator space 
    # to joint space waypoints for the robot to execute the move
    #7. Use the trajectory planner to generate a trajectory for the robot to move from its
    # current waypoint to the next waypoint target using a fifth-order spline trajectory
    #8. query the trajectory planner for the next trajectory segment to execute and send the joint angle commands to the robot
    """!
    @brief uses asyncio to run cooperative multitasking. to run the main control loop of the chess robot software, which includes:
        cv task:
        - running the computer vision system to detect the move made on the chess board

        endgame effector cpu task:
        - validating the detected move and updating the chess board state
        - generating chessspace waypoints for the move using the chess board's parsemove() function
        - converting the chessspace waypoints to manipulator space waypoints using the robot motion planner's parse_chesswaypoints() function
        - converting the manipulator space waypoints to joint space waypoints using the inverse kinematics function
        - using the trajectory planner to generate a trajectory for the robot to move from its current waypoint to the next waypoint target using a fifth-order spline trajectory
        - querying the trajectory planner for the next trajectory segment to execute and sending the joint angle commands to the robot
        
        servo controller task:
        - managing the robot's servo control loop to execute the 
        joint angle commands generated by the trajectory planner   
        
        ui task:
        - updating the UI with the current board state and any relevant information
       
        low-level sensor control task:
        - manage the electromagnetic
        and limit switch and possible LEDS
    """
    #ports for the servo controllers, adjust as needed based on your system configuration
    port55 = "COM3"  # Serial port for 55-series servos (orange)
    portff = "COM4"  # Serial port for FF-series servos (black)
    #initialize the chess board and robot motion planner
    chess_board = ChessBoard()
    motion_planner = RobotMotionPlanner()
    
    #initialize servo controller (optional - will be None if ports unavailable)
    servo_controller = None
    try:
        servo_controller = ServoController(port55, portff)
    except Exception as e:
        print(f"Warning: Could not initialize ServoController: {e}. Servo control will be skipped.")
    
    #initialize low level hardware controllers (optional)
    EMAG = None
    try:
        EMAG = Electromagnet(pin=17)
    except Exception as e:
        print(f"Warning: Could not initialize Electromagnet: {e}. Electromagnet control will be skipped.")
    #########################################################
    #event and queue definitions for inter-task communication
    #########################################################
    #events that represent flags for inter-task communication and synchronization
    begin_game = asyncio.Event()  # Event to signal the start of the game after initialization
    use_cv = asyncio.Event()  # Event to signal whether we will use CV or manual input for moves
    ready4cv = asyncio.Event() # Event to signal when the system is ready for CV to detect the next move,
    #updated by the endgame effector CPU task and read by the CV task to know when to run the CV detection for the next move
    ready2move = asyncio.Event()  # Event to signal that the opponents move is complete 
    #meaning the robot can process the current move and execute the next move
    emag_on = asyncio.Event()  # Event to signal when to turn on the electromagnet for piece manipulation
    emag_off = asyncio.Event()  # Event to signal when to turn off the electromagnet
    move_completed = asyncio.Event()  # Event to signal that the robot has completed its move 
    servo_mode = asyncio.Event()  # Event to signal when to switch the servo control mode
    valid_move = asyncio.Event()  # Event to signal that the detected move has been validated and parsed successfully
    calibrate_servos = asyncio.Event() # Event to signal when to run the servo calibration routine, which involves setting the servo offsets for each servo based on the current position of the robot arm
    calibrate_servos2 = asyncio.Event() # Event to signal when to run the second part of the servo calibration routine, which involves moving each servo to its min and max angles to verify the limits and adjust as needed   
    kill_switch = asyncio.Event()  # Event to signal when to shut down all tasks and exit the program
    #########################################################
    #queues to hold data that needs to be passed between tasks
    winner = asyncio.Queue() # Queue for the winner of the game,
    #updated by the endgame effector CPU task and read by the UI task to display
    opponent_move = asyncio.Queue() # Queue for opponent moves inputted in UI or detected by CV 
    #depending on the game mode
    theta_vector = asyncio.Queue() # Queue for the current joint angles of the robot, 
    #thetas read by the motor
    actual_thetas = asyncio.Queue() # Queue for the actual joint angles of the robot,
    #updated by the servo controller task reading the servo positions and read by the endgame eff
    #updated by the cpu task and read by the servo controller task for motion execution
    detected_fen = asyncio.Queue() # Queue for the detected FEN string after a move is made,
    #updated by the CV task and read by the endgame effector CPU task for move validation
    winner = asyncio.Queue() # Queue for the winner of the game, 
    #updated by the endgame effector CPU task and read by the UI task to display
    update_ui_boardstate = asyncio.Queue() # Queue for the current board state to be displayed in the UI,
    update_ui_robot_waypoints = asyncio.Queue() # Queue for the current robot waypoints to be displayed in the UI,
    update_ui_move_list = asyncio.Queue() # Queue for the move list to be displayed in the UI
    promotion_piece = asyncio.Queue() # Queue for the piece type to promote to in a pawn promotion scenario,
    #updated by the endgame effector CPU task and read by the UI task to display promotion options and get 
    #user input to place the piece in the promotion square
    ###########################################################################

    #asyncio tasks
    async def servo_controller_task():
        in_calibration_mode = False
        while True:
            # Check for kill switch - stop all motors immediately
            if kill_switch.is_set():
                print("KILL SWITCH ACTIVATED - Stopping all motors!")
                if servo_controller is not None:
                    # Move all servos to neutral/safe position
                    try:
                        neutral_thetas = [150, 150, 150, 150]  # Safe neutral position
                        servo_controller.update_servo_positions(neutral_thetas)
                    except Exception as e:
                        print(f"Error stopping servos: {e}")
                # Keep waiting until kill switch is cleared from UI
                await asyncio.sleep(0.1)
                continue
            
            # Check if calibration mode is requested
            if calibrate_servos.is_set():
                in_calibration_mode = True
                print("Entering servo calibration mode...")
                calibrate_servos.clear()
            
            # Main servo control
            if not in_calibration_mode:
                # Normal operation: wait for servo commands (with timeout to avoid blocking)
                try:
                    await asyncio.wait_for(servo_mode.wait(), timeout=0.01)
                    if servo_controller is not None:
                        await actual_thetas.put(servo_controller.get_servo_positions()) # Read actual servo positions for feedback
                    current_thetas = await theta_vector.get()  # Get the next set of joint angles to move to    
                    print(f"Updating servo positions to: {current_thetas}")
                    if servo_controller is not None:
                        servo_controller.update_servo_positions(current_thetas)
                    else:
                        print("  (Servo control not available - skipping)")
                    servo_mode.clear()
                except asyncio.TimeoutError:
                    pass  # No servo command, continue
            else:
                # Calibration mode
                if servo_controller is not None:
                    servo_controller.set_servo_offsets()
                    home_thetas = [150, 150, 150, 150]  # Example home position
                    servo_controller.update_servo_positions(home_thetas)
                    await asyncio.sleep(2)  # Wait for servos to move
                    servo_controller.set_servo_offsets()
                
                if calibrate_servos2.is_set():
                    print("Calibration complete.")
                    calibrate_servos2.clear()
                    in_calibration_mode = False
            
            await asyncio.sleep(0.01)  # Prevent busy-waiting
    
    async def cv_task():
        classifier = board_to_fen.load_trained_classifier()
        empty_board_ref = board_to_fen.load_empty_board_reference()

        while True:
            await use_cv.wait()  # Wait until CV mode is enabled
            #run the computer vision system to detect the move 
            #put the detected move in the chessboard object to validate it and update the chess board state
            await ready4cv.wait()  # Wait until the system is ready for CV to detect the next move
            print("CV Task: Starting move detection...")

            fen, _, debug = board_to_fen.detect_fen_once(
                empty_board_ref=empty_board_ref,
                classifier=classifier,
            )

            if fen is not None:
                print(f"CV Task: Detected FEN: {fen}")
                await detected_fen.put(fen)
            else:
                print(f"CV Task: Detection failed - {debug}")
            await asyncio.sleep(0.1)


    async def endgameeffector_cpu_task():
        # Create queues and events dictionaries for FSM
        queues = {
            'opponent_move': opponent_move,
            'detected_fen': detected_fen,
            'theta_vector': theta_vector,
            "actual_thetas": actual_thetas,
            'update_ui_boardstate': update_ui_boardstate,
            'update_ui_robot_waypoints': update_ui_robot_waypoints,
            'winner': winner
        }
        events = {
            'begin_game': begin_game,
            'ready2move': ready2move,
            'servo_mode': servo_mode,
            'use_cv': use_cv,
            'ready4cv': ready4cv,
            'emag_on': emag_on,
            'emag_off': emag_off,
            'valid_move': valid_move,
            'move_completed': move_completed,
        }
        # Create and run the FSM
        fsm = EndgameEffectorFSM(queues, events, chess_board, motion_planner)
        await fsm.run()
    
    async def ui_task():
        # Start the uvicorn web server for the FastAPI app
        config = uvicorn.Config(ui_app, host="127.0.0.1", port=8000, log_level="info")
        server = uvicorn.Server(config)
        await server.serve()

    async def lowlevel_sensorcontrol_task():
        while True:
            await emag_on.wait()  # Wait for the signal to turn on the electromagnet
            print("Electromagnet ON for piece manipulation.")
            if EMAG is not None:
                EMAG.on()
            emag_on.clear()  # Reset for next use
            
            await emag_off.wait()  # Wait for the signal to turn off the electromagnet
            print("Electromagnet OFF after piece manipulation.")
            if EMAG is not None:
                EMAG.off()
            emag_off.clear()  # Reset for next use


    ui_queues = {
        'detected_fen': detected_fen,
        'winner': winner,
        'update_ui_boardstate': update_ui_boardstate,
        'update_ui_robot_waypoints': update_ui_robot_waypoints,
        'update_ui_move_list': update_ui_move_list,
        'opponent_move': opponent_move,
    }
    ui_events = {
        'begin_game': begin_game,
        'ready2move': ready2move,
        'move_completed': move_completed,
        'valid_move': valid_move,
        'use_cv': use_cv,
        'calibrate_servos': calibrate_servos,
        'calibrate_servos2': calibrate_servos2,
        'kill_switch': kill_switch,
    }
    init_ui_runtime(ui_queues, ui_events, chess_board, motion_planner)

    #run the tasks concurrently
    async def run_all_tasks():
        await asyncio.gather(
            cv_task(),
            servo_controller_task(),
            endgameeffector_cpu_task(),
            ui_task(),
            lowlevel_sensorcontrol_task()
        )
    
    asyncio.run(run_all_tasks())
        
if __name__ == "__main__":
    main()

